### ISSUE TITLE
[Feature request] Only reload on request

### ISSUE THREAD

**Issue by jjant** [rksm/hot-lib-reloader-rs#17]
I'm writing a sort of game engine and I would like to be able to only reload game code on request (say, when a user presses Cmd+R).
Is this currently possible with the library? I couldn't figure it out.

Thanks!

**Comment by rksm** [comment]
You can block reloads like it is done here: https://github.com/rksm/hot-lib-reloader-rs/blob/master/tests/lib-loader-test.rs#L48. As long as you don't drop the `update_blocker` token no update will happen, potentially indefinitely. [The reload event example](https://github.com/rksm/hot-lib-reloader-rs/blob/master/examples/reload-events/src/main.rs#L49) shows how you can do this in a separate async task (or with thread it work the same).

You can build a mechanism around that to block updates by default and then when a key is pressed you drop the token (if there is one) so that the update will run.
