### ISSUE TITLE
`hot_functions_from_file` doesn't find functions created in a macro

### ISSUE THREAD

**Issue by jjant** [rksm/hot-lib-reloader-rs#18]
I'm trying to hide some of the moving parts by creating the exported, no_mangle'd functions in a macro (exposed from a library) but when I attempt to use it in my reloadable lib, the `hot_functions_from_file` function doesn't find them.

```rust
// mod file1
#[macro_export]
macro_rules! make_exports {
  #[no_mangle]
  pub fn f() -> i32 { 42 }
}

// mod file2
make_exports!();

// main
mod hot_lib {
  hot_functions_from_file("file2/src/lib.rs");
}

fn main() {
  hot_lib::f(); // function not found in `hot_lib`
}
```

**Comment by rksm** [comment]
So one limitation of the approach used with the `hot_module` macro is that expansion of macros in the target file is not supported. This means we are looking literally for

```
#[no_mangle]
pub fn f() -> i32 { ... }
```

We ignore the function body but use the signature to generate proxy functions in the context of `hot_lib`.

Now depending on what you want there might still be ways around this.

## manual signatures

One option is to directly specify the signatures in hot_lib itself:

Instead of doing

```rust
#[hot_lib_reloader::hot_module(dylib = "lib_crate")]
mod hot_lib {
  hot_functions_from_file!("file2/src/lib.rs");
}
```

you can do

```rust
#[hot_lib_reloader::hot_module(dylib = "lib_crate")]
mod hot_lib {
    #[hot_function]
    pub fn f() -> i32 {}
}
```

I.e. you have to make sure that the function signatures of the reloadable functions matches what is exported from the dynamic library.

## `ignore_no_mangle`

I just pushed [a change](https://github.com/rksm/hot-lib-reloader-rs/commit/baf4e5ad493aa276be5368c89d6eec9b8d787248) to master that allows for a syntax like

```
hot_functions_from_file!("lib/src/lib.rs", ignore_no_mangle = true);
```

This is experimental and not part of a release yet. I will remove it if it turns out not to be useful for your use case.

This will disable the `#[no_mangle]` restriction when reading files from `lib.rs`. Functions will still need to be `pub` and the lib still needs to export symbols representing those functions unmangled but you could have a different way of ensuring that, e.g. a `build.rs` script.

Also note that the file you target from `hot_module` does not necessarily need to be the place where the "real" functions are defined and/or exported. All we do is to read the signatures from that file. So if you have some way of generating this this would be another option.
