### ISSUE TITLE
Windows sometimes doesn't work

### ISSUE THREAD

**Issue by cdecompilador** [rksm/hot-lib-reloader-rs#19]
All the examples provided work except the bevy one, 
```
LINK : fatal error LNK1104: can't open file '.\hot-lib-reloader-rs\examples\bevy\target\debug\deps\systems.dll
```

**Comment by rksm** [comment]
Just wanted to say that I've seen this issue but not have had time to look into that. It's on my todo list.

**Comment by rksm** [comment]
Sorry took me a while.

I believe what you ran into is the issue described here: https://github.com/rksm/hot-lib-reloader-rs/tree/master/examples/bevy#library-files-on-windows-get-locked-while-the-app-is-running-and-there-is-a-permission-error-when-they-change.

So on windows doing

```
$ cargo watch -w systems -w components -x "build -p systems --features dynamic"
$ cargo run --features reload --target-dir "target-bin"
```

should fix the issue.

Please reopen if the issue is not fixed with the above.
